[package]
name = "swiftdns"
version = "0.16.0"
authors = ["chris9740"]
edition = "2021"
description = "Local DNS resolver with DoH, Tor routing, and privacy filtering"
license-file = "LICENSE"

[profile.dev]
lto = false
opt-level = 0
debug = 0
incremental = true
codegen-units = 256
panic = "abort"

[profile.release]
strip = true
lto = false
codegen-units = 256

[dependencies]
tokio = { version = "1", default-features = false, features = ["macros", "rt"] }
clap = { version = "4.0", features = ["derive", "cargo"] }
reqwest = { version = "0.11", default-features = false, features = [
    "socks",
    "rustls-tls",
] }
serde = { version = "1.0.159", default-features = false, features = ["derive"] }
hickory-proto = { version = "0.25.2", default-features = false }
bytes = "1.4.0"
wildmatch = "2.1.1"
chrono = "0.4.24"
tabwriter = "1.2.1"
idna = "0.4.0"
anyhow = "1.0.72"
colored = "2.0.4"
toml = "0.8.22"
thiserror = "2.0.12"
tokio-rustls = "0.24"
rustls-native-certs = "0.6"
url = "2.5.4"

[dev-dependencies]
assert_cmd = "2.0.17"
predicates = "3.1.3"
tokio-test = "0.4.4"

[package.metadata.deb]
revision = ""
maintainer-scripts = "debian/"
systemd-units = { enable = true }
assets = [
    [
        "target/release/swiftdns",
        "/usr/bin/",
        "755",
    ],
    [
        "assets/filters/whitelist.list",
        "/etc/swiftdns/filters/whitelist.list",
        "644",
    ],
]
conf-files = [
    "/etc/swiftdns/config.toml",
    "/etc/swiftdns/filters/whitelist.list",
]
