FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    curl \
    clang \
    mold \
    tor \
    dnsutils \
    python3 \
    python3-pip \
    git \
    netcat-openbsd \
    make \
    nodejs \
    npm

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN pip3 install --break-system-packages robotframework

WORKDIR /workspace
