#!/bin/bash

#DEBHELPER#

# Create system-user "swiftdns" along with a group with the same name
adduser --system --group --quiet swiftdns

mkdir -p /etc/swiftdns/rules

chown swiftdns:swiftdns -R /etc/swiftdns
chmod 755 -R /etc/swiftdns

exit 0
