# Configuration file used in development

address = "127.0.0.1:5053"

[resolver]
url = "https://cloudflare-dns.com/dns-query"
bootstrap_ips = ["1.1.1.1:443"]

[tor]
enabled = false
address = "127.0.0.1:9050"
