# Configuration file used in development

scope = "Local"
address = "127.0.0.1:5053"

[resolver]
url = "https://dns.nextdns.io/dns-query"
bootstrap_ips = ["45.90.28.0:443", "45.90.30.0:443"]

[tor]
enabled = false
address = "127.0.0.1:9050"
