[[providers]]
name = "Cloudflare"
modes = [
    { name = "Standard", ip = "1.1.1.1" },
    { name = "Safe", ip = "1.1.1.2" },
    { name = "Clean", ip = "1.1.1.3" },
]
url = "https://{ip}/dns-query"

[[providers]]
name = "Google"
modes = [{ name = "Standard", ip = "8.8.8.8" }]
url = "https://{ip}/resolve"

[[providers]]
name = "Quad9"
modes = [{ name = "Standard", ip = "9.9.9.9" }]
url = "https://{ip}:5053/dns-query"
