[[providers]]
name = "Cloudflare"
modes = [
    { name = "Standard", ip = "1.1.1.1" },
    { name = "Safe", ip = "1.1.1.2" },
    { name = "Clean", ip = "1.1.1.3" },
]
url = "https://{ip}/dns-query?name={name}&type={type}"

[[providers]]
name = "Google"
modes = [{ name = "Standard", ip = "8.8.8.8" }]
url = "https://{ip}/resolve?name={name}&type={type}"

[[providers]]
name = "NextDNS"
modes = [{ name = "Standard", ip = "dns.nextdns.io" }]
url = "https://{ip}/7b3193?name={name}&type={type}"
