name: Rust Testing

on:
    push:
        branches: [master, dev, revision, feat/*]
    pull_request:
        branches: [master, dev, revision, feat/*]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable

            - name: Install ShellCheck
              run: |
                  sudo apt-get update
                  sudo apt-get install -y shellcheck

            - name: Run ShellCheck
              run: |
                  shellcheck .github/hooks/prepare-commit-msg

            - name: Install Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: Install Python dependencies
              run: |
                  pip install -r tests/requirements.txt

            - name: Build and test
              run: |
                  cargo build --verbose
                  cargo test --verbose
                  python3 tests/compare_dns.py
