name: Rust Testing

on:
    push:
        branches: [master, revision, e2e]
    pull_request:
        branches: [master, revision, e2e]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  override: true
                  components: clippy, rustfmt

            - name: Install ShellCheck
              run: |
                  sudo apt-get update
                  sudo apt-get install -y shellcheck

            - name: Run ShellCheck
              run: |
                  shellcheck .github/hooks/prepare-commit-msg

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y clang mold

            - name: Prepare cargo config
              run: |
                  # Remove sccache config for CI
                  sed -i '/\[build\]/,+1d' .cargo/config.toml

            - name: Run tests
              run: |
                  cargo test
